cube_file="../../STM8S001-TEST/dive.txt"
programmer="stlinkv2"
std_path="/home/grandmother/Downloads/STM8S_StdPeriph_Lib/Libraries/STM8S_StdPeriph_Driver/"

no_dce=false
dependencies=[]
ucsim_port=11111
