mcu="stm8s103f3"
programmer="stlinkv2"
std_path="~/Downloads/STM8S_StdPeriph_Lib/Libraries/STM8S_StdPeriph_Driver/"
dependencies=['FLASH', 'UART1', 'TIM2', 'GPIO']
log_level=10

[ucsim]
port=11111

[ucsim.interfaces.uart.1]
iport=11112
raw=true
